---
- name: shutdown nodes
  hosts: nas1
  ignore_errors: true
  tasks:
  - name: shutdown
    community.general.shutdown:
      delay: 0

- name: shutdown nodes
  hosts: soc1
  ignore_errors: true
  tasks:
  - name: shutdown
    community.general.shutdown:
      delay: 0

- name: shutdown nodes
  hosts: mon1
  ignore_errors: true
  tasks:
  - name: shutdown
    community.general.shutdown:
      delay: 0

- name: shutdown nodes
  hosts: pve1
  ignore_errors: true
  tasks:
  - name: shutdown
    community.general.shutdown:
      delay: 5
