---
- name: shutdown nodes
  hosts: mon1
  tasks:
  - name: shutdown
    community.general.shutdown:
      delay: 0

- name: shutdown nodes
  hosts: jump01
  tasks:
  - name: shutdown
    community.general.shutdown:
      delay: 2

- name: shutdown nodes
  hosts: pve1
  tasks:
  - name: shutdown
    community.general.shutdown:
      delay: 7
